"'Product View' As screen":

    "Gallery2 As gallery.'BrowseLayout_Vertical_TwoTextOneImageVariant_ver4.0'":
        Items: ='Product registration'
        Layout: =Layout.Vertical
        TemplatePadding: =0
        TemplateSize: =Min(160, Self.Height - 60)
        Y: =561
        ZIndex: =1

        Image3 As image:
            Height: =128
            Image: =ThisItem.'Product image'
            OnSelect: =Select(Parent)
            Width: =128
            X: =16
            Y: =(Parent.TemplateHeight / 2) - (Self.Height / 2)
            ZIndex: =1

        Title2 As label:
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.count
            VerticalAlign: =VerticalAlign.Top
            Width: =Parent.TemplateWidth - Image3.Width - 104
            X: =Image3.X + Image3.Width + 24
            Y: =44
            ZIndex: =2

        Subtitle2 As label:
            Height: =Self.Size * 1.8
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Product name'
            VerticalAlign: =VerticalAlign.Top
            Width: =Title2.Width
            X: =155
            Y: =91
            ZIndex: =3

        Separator2 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =5

    Dropdown2 As dropdown:
        AllowEmptySelection: =true
        Height: =70
        Items: =["abc","def"]
        Size: =21
        Width: =575
        X: =40
        Y: =40
        ZIndex: =2

